### ISSUE TITLE
Reset rules for browser

### ISSUE THREAD

**Issue by mariosknl** [Meltrust/forms-project#2]
you better insert the following lines of code in the beginning of your css to reset the rules for each browser so you can have control of the appearance you website want to have.

*{
margin:0;
padding:0;
box-sizing: border-box;
}

**Comment by mariosknl** [comment]
and also try to use the shorthand for the background property in css to avoid repeating yourself in many lines

**Comment by Meltrust** [comment]
I'll keep in mind for the next project! Ty!!
