### ISSUE TITLE
To make the code better

### ISSUE THREAD

**Issue by kirokoNjenga** [Meltrust/forms-project#4]
**Good work done on the project**
-quick things to make  your code better
_add comment on your code to make navigation  in your code easy
_on your README file have a look at the link below
[Readme_file](https://github.com/Samkiroko/mint-sign-up)

**Comment by Meltrust** [comment]
![Screenshot](https://user-images.githubusercontent.com/57421823/70156403-7fd8f400-1679-11ea-9be6-7495bb16014e.png)

Fixed! Ty!
